services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - nginx-logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nginx-logs:
    driver: local

networks:
  app-network:
    driver: bridge
